--1
SELECT LAST_NAME "Last Name"
from EMPLOYEES
where LOWER(SUBSTR(LAST_NAME, 2, 1)) IN('a','e','i','o','u');

--2
SELECT (FIRST_NAME||' '||LAST_NAME) Fullname, HIRE_DATE
FROM EMPLOYEES
WHERE ("LOWER"(FIRST_NAME) like '%i%' or LAST_NAME not like 'S%') and HIRE_DATE < '03-OCT-2006';

--3
SELECT DEPARTMENT_ID, MIN(HIRE_DATE) "First Hiring Date", MAX(HIRE_DATE) "Last Hiring Date", round(avg(salary), 2) "Average Salary"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 6000 and AVG(SALARY) < 12000 and DEPARTMENT_ID is not NULL;

--4
select LOCATION_ID, COUNT(MANAGER_ID) "Number of Managers"
FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY LOCATION_ID;

--5
SELECT COUNTRY_ID, COUNTRY_NAME 
from COUNTRIES
where LENGTH(COUNTRY_NAME)<8;


